#!/bin/bash
echo "-----------------------------------------------------------------------"
echo "Delete sym links"
rm -f  usr/bin/create_autostart_launcher
echo "Symbolic links deleted."
echo "-----------------------------------------------------------------------"
exit 0
