.\" Manpage for primtux-no-sudo-password.
.\" Contact cyrille@cbiot.fr to correct errors or typos.
.TH man 8 "2 March 2021" "1.0" "primtux-no-sudo-password man page"
.SH NAME primtux-no-sudo-password
Permet à l'utilisateur administrateur d'un système Printux de lancer sudo sans mot de passe.
.SH SYNOPSIS
Pas d'utilitaire juste un fichier de configuration installé dans /etc/sudoers.d/
.SH DESCRIPTION
Suprresion du mot de passe sudo pour l'utilisateur "administrateur" d'une distribution Primtux (https://primtux.fr/)
.SH OPTIONS
Aucune option car aucun utilitaire, seul un fichier de configuration d'installé.
.SH SEE ALSO
sudo(8), sudoers(5), sudo.conf(5)
.SH BUGS
No known bugs.
.SH AUTHOR
Cyrille Biot (cyrille@cbiot.fr)
